[package]
name = "epi4you"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.6"
clap-cargo = "0.13.0"
home = "0.5.5"
serde_json = "1.0.107"
serde = { version = "1.0.107", features = ["derive"] }
sqlite = "0.31.1"