FROM almalinux:9

RUN dnf install -y \
    make \
    python3 \
    python3-pip \
    && dnf clean all

COPY requirements.txt /tmp/requirements.txt

RUN python3 -m pip install --no-cache-dir --upgrade pip \
    && python3 -m pip install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /workspace

CMD ["make", "-C", "docs", "html"]
